# Generated by Django 5.2.7 on 2025-10-23 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('entity', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_leaving', models.DateField()),
                ('bus_no', models.CharField(max_length=20)),
                ('bus_pass_no', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_drop_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_app.stop')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('alternate_no', models.CharField(blank=True, max_length=15, null=True)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('entity', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern')], max_length=20)),
                ('emp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField()),
                ('working_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_drop_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_app.stop')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.stop')),
            ],
        ),
    ]
