# Generated by Django 5.2.6 on 2025-10-24 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0002_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='password',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='drop_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
