# Generated by Django 5.2.6 on 2025-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0004_actionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='description',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='performed_by',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
