# Generated by Django 5.2.6 on 2025-10-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0005_rename_description_actionlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='drop_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
