# Generated by Django 5.2.6 on 2025-10-27 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0006_alter_bus_bus_no_alter_bus_drop_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_app.stop'),
        ),
    ]
