# Generated by Django 5.2.6 on 2025-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0007_alter_bus_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='stop',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
