# Generated by Django 5.2.6 on 2025-10-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0008_alter_bus_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
